version: '3'
services:

  fastapi:
    build: .
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic upgrade head && uvicorn statistic.main:app --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image:
      "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_USER: ${POSTGRES_USER-user}
      POSTGRES_DB: ${POSTGRES_USER-database}


volumes:
  postgres_data:
