"""Create table Statistic

Revision ID: ad0bc562809e
Revises: 54d7ce2849ef
Create Date: 2022-12-05 15:17:19.663362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0bc562809e'
down_revision = '54d7ce2849ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistic_date'), 'statistic', ['date'], unique=False)
    op.create_index(op.f('ix_statistic_id'), 'statistic', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistic_id'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_date'), table_name='statistic')
    op.drop_table('statistic')
    # ### end Alembic commands ###
